//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParseFlatFileEntity : DbContext
    {
        public ParseFlatFileEntity()
            : base("name=ParseFlatFileEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PIT_App_ProcessRunControl> PIT_App_ProcessRunControl { get; set; }
        public virtual DbSet<PIT_Meta_ProcessDefn> PIT_Meta_ProcessDefn { get; set; }
        public virtual DbSet<PIT_Meta_ProjectCategories> PIT_Meta_ProjectCategories { get; set; }
        public virtual DbSet<PIT_Meta_ProjectSubCategories> PIT_Meta_ProjectSubCategories { get; set; }
        public virtual DbSet<PIT_Stg_ParsingHdr> PIT_Stg_ParsingHdr { get; set; }
        public virtual DbSet<PIT_Stg_ParsingItemDetail> PIT_Stg_ParsingItemDetail { get; set; }
        public virtual DbSet<PIT_Stg_TxDotProjectItems> PIT_Stg_TxDotProjectItems { get; set; }
        public virtual DbSet<PIT_Stg_TxDotProjects> PIT_Stg_TxDotProjects { get; set; }
    }
}
