//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIT_Stg_TxDotProjectItems
    {
        public int DataLoadItemID { get; set; }
        public int DataLoadID { get; set; }
        public string AltCode { get; set; }
        public string ItemNo { get; set; }
        public string DESCode { get; set; }
        public string Description { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> ApproxQuantity { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual PIT_Stg_TxDotProjects PIT_Stg_TxDotProjects { get; set; }
    }
}
