//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIT_Stg_ParsingItemDetail
    {
        public int DataLoadItemID { get; set; }
        public Nullable<int> DataLoadID { get; set; }
        public string ALT { get; set; }
        public string ItemNO { get; set; }
        public string DESCode { get; set; }
        public string ItemDescription { get; set; }
        public string Unit { get; set; }
        public string ApproximateQantities { get; set; }
        public string BidPrice { get; set; }
        public string Amount { get; set; }
        public string Seq { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual PIT_Stg_ParsingHdr PIT_Stg_ParsingHdr { get; set; }
    }
}
