//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIT_App_ProcessRunControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIT_App_ProcessRunControl()
        {
            this.PIT_Stg_TxDotProjects = new HashSet<PIT_Stg_TxDotProjects>();
        }
    
        public System.Guid ProcessRunControlID { get; set; }
        public string ProcessID { get; set; }
        public System.DateTime BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
        public string DataColumn { get; set; }
        public string DataColumn1 { get; set; }
        public string DataColumn2 { get; set; }
        public string DataColumn3 { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual PIT_Meta_ProcessDefn PIT_Meta_ProcessDefn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIT_Stg_TxDotProjects> PIT_Stg_TxDotProjects { get; set; }
    }
}
