//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIT_Stg_TxDotProjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIT_Stg_TxDotProjects()
        {
            this.PIT_Stg_TxDotProjectItems = new HashSet<PIT_Stg_TxDotProjectItems>();
        }
    
        public int DataLoadID { get; set; }
        public System.Guid ProcessRunControlID { get; set; }
        public string County { get; set; }
        public string Highway { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<decimal> DBEGoal { get; set; }
        public string ProjectNumber { get; set; }
        public string Type { get; set; }
        public Nullable<int> TimeForCompletion { get; set; }
        public Nullable<decimal> Guaranty { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<System.DateTime> BidsReceivedUntil { get; set; }
        public Nullable<System.DateTime> BidsWillBeOpened { get; set; }
        public string DeliverBidsTo { get; set; }
        public string PSEContact { get; set; }
        public bool ProjectExistsAlready { get; set; }
        public bool ActiveQuotesExistAlready { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual PIT_App_ProcessRunControl PIT_App_ProcessRunControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIT_Stg_TxDotProjectItems> PIT_Stg_TxDotProjectItems { get; set; }
    }
}
