//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseFlatFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIT_Stg_ParsingHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIT_Stg_ParsingHdr()
        {
            this.PIT_Stg_ParsingItemDetail = new HashSet<PIT_Stg_ParsingItemDetail>();
        }
    
        public int DataLoadID { get; set; }
        public int ProcessRunControlID { get; set; }
        public string County { get; set; }
        public string Highway { get; set; }
        public string length { get; set; }
        public string Control { get; set; }
        public string DBEGoal { get; set; }
        public string ProjectNumber { get; set; }
        public string Type { get; set; }
        public string TimeForCompletion { get; set; }
        public string Guaranty { get; set; }
        public string EstimatedCost { get; set; }
        public string BidsReceivedUntil { get; set; }
        public string BidsWillBeOpened { get; set; }
        public string MailOrDeliverBidsTo { get; set; }
        public string PandSEContact { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ElectronicBiddingWebsite { get; set; }
        public string SBEGoal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIT_Stg_ParsingItemDetail> PIT_Stg_ParsingItemDetail { get; set; }
    }
}
